### PR TITLE
Bump version to 1.10.0

### PR DESCRIPTION
**Pull request by kordejong**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [ ] Bumped the build number (if the version is unchanged)
* [x] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by kordejong** [comment]
@conda-forge-admin, please rerender

**Comment by kordejong** [comment]
@hkaiser I am preparing for the upcoming release of HPX. All seems fine (which is great!) except for the osx/arm64 build. CMake fails to configure the project because it is in cross-compiling mode. This seems related: https://cmake.org/cmake/help/latest/command/try_run.html#behavior-when-cross-compiling

I have no experience with cross-compiling. I wonder whether in this case, the HPX scripts must be updated, or whether we must pass the mentioned cache variables on the command line? Do you have any insights?

**Comment by hkaiser** [comment]
> @hkaiser I am preparing for the upcoming release of HPX. All seems fine (which is great!) except for the osx/arm64 build. CMake fails to configure the project because it is in cross-compiling mode. This seems related: https://cmake.org/cmake/help/latest/command/try_run.html#behavior-when-cross-compiling
> 
> I have no experience with cross-compiling. I wonder whether in this case, the HPX scripts must be updated, or whether we must pass the mentioned cache variables on the command line? Do you have any insights?

Can you give me the error log for this?

**Comment by kordejong** [comment]
@hkaiser The macos/arm64 build now succeeds, great. For some reason the Windows build does not finish anymore. I can't think of a reason, given your changes to the CMake scripts, why this happens.

**Comment by hkaiser** [comment]
> @hkaiser The macos/arm64 build now succeeds, great. For some reason the Windows build does not finish anymore. I can't think of a reason, given your changes to the CMake scripts, why this happens.

It might just got stuck somewhere. Please try re-triggering the build.

**Comment by kordejong** [comment]
Yeah, I have tried that several times now and it times out after six hour each time.

**Comment by kordejong** [comment]
With rc3 all builds succeed. I will keep this PR open until 1.10.0 is released.

**Pull request merged**
